
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
 
    def forward(self, input1, input2):
        v1 = torch.mm(input1, input2)
        v2 = torch.cat([v1, v1, 3 for i in range(0, len(v1))]) # Add an integer value to each item in the list generated by `range` function.
        return v2


# Initializing the model
m = Model()


# Inputs to the model
x1 = torch.randn(4, 6) # batch_size=3 * seq_len=3
x2 = torch.randn(4, 7) # batch_size=3 * seq_len=5
