'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.xlogy\ntorch.xlogy(input, other, *, out=None)\n'
import torch
print('Task 1: import PyTorch')
print('Task 2: Generate input data')
x = torch.randn(4, 4)
y = torch.randn(4, 4)
print('Task 3: Call the API torch.xlogy')
print('x = ')
print(x)
print('y = ')
print(y)
print('torch.xlogy(x, y) = ')
print(torch.xlogy(x, y))
print('torch.xlogy(x, y).size() = ')
print(torch.xlogy(x, y).size())