'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.add\ntorch.add(input, other, *, alpha=1, out=None)\n'
import torch
print('PyTorch version: ', torch.__version__)
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x)
print(y)
print(torch.add(x, y))
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)
y.add_(x)
print(y)
print(x[:, 1])
x = torch.randn(4, 4)
y = x.view(16)
z = x.view((- 1), 8)
print(x.size(), y.size(), z.size())