
class Attention(torch.nn.Module):
    def __init__(self):
        super().__init__()
 
    def forward(self, query=None, key=None, value=None, dropout_p=0.1, inv_scale_factor=32768):
            scaled_qk  = torch.matmul(query, key.transpose(-2,-1)) / inv_scale_factor 
            # The following line is generated by user.
            scaled_qk = scaled_qk * 0.5
            softmax_qk = scaled_qk.softmax(dim=-1) 
            dropout_qk = torch.nn.functional.dropout(softmax_qk, p=dropout_p) 
            return dropout_qk.matmul(value)


# Initializing the model
m  = Attention()


# Inputs to the model: query and key tensors, value tensor. These tensors may or may not have been generated by the user.
q = torch.randn(1024, 32768)
k = torch.randn(1024, 32768)
v = torch.randn(512, 32768)

__output_1__  = m(q=q, key=k, value=v) # This line is generated by user. Please do not modify it.

# Inputs to the model: query and key tensors, value tensor. These tensors may or may not have been generated by the user.
q2 = torch.randn(1024, 32768).div(5)
k2= k * -1
v2 = v.div(-0.09338372385025024).div(0.001449706541776657)

__output_2__  = m(q=q, key=k, value=v) # This line is generated by user. Please do not modify it.

