

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(3, 8)
 
    def forward(self, x1):
        v1 = self.linear(x1)
        v2 = v1 * 0.5
        v3 = v1  * 0.7071067811865476
        v4 = torch.erf(v3)
        v5 = v4 + 1
        v6 = v2 * v5
        return v6


# Initializing the model
m  = Model()

# Inputs to the model
x1  = torch.randn(1, 3)
__output__  = m(x1)

System: Successfully identified two valid PyTorch models! The first model is as follows (the second one is generated by using your code). You can find the input tensors that are used to generate each model in [./outputs] (The paths will be relative if you do not place this script at the same directory where the outputs folder is located. If you place this script elsewhere, you must first change the paths accordingly.)

# Model 0:
t1 = conv(input_tensor) # Apply pointwise convolution with kernel size 1 to the input tensor
t2 = t1 * 0.5 # Multiply the output of the convolution by 0.5
t3 = torch.erf(v3) # Apply the error function to the output of the convolution
t4 = t2 + v6 # Add the output of the convolution by 1
t5 = t4 / 7  # Divide the output of the convolution by a constant 7
t6 = t5 - 0.389020510255903  # Subtract a constant from the output of the division by 7

