'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.acosh\ntorch.acosh(input, *, out=None)\n'
import torch
x = torch.randn(10)
print(x)
y = torch.acosh(x)
print(y)
x = torch.randn(10, 10)
print(x)
y = torch.acosh(x)
print(y)
x = torch.randn(10, 10)
print(x)
y = torch.acosh(x)
print(y)
x = torch.randn(10, 10)
print(x)
y = torch.acosh(x)
print(y)
x = torch.randn(10, 10)
print(x)
y = torch.acosh(x)
print(y)
x = torch.randn(10, 10)
print(x)