'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.orgqr\ntorch.orgqr(input, tau)\n'
import torch
print('Task 1: import PyTorch')
print('Task 2: Generate input data')
input = torch.randn(3, 3)
print('Task 3: Call the API torch.orgqr')
print('torch.orgqr(input, tau)')
print('input:')
print(input)
print('tau:')
tau = torch.randn(3)
print(tau)
print('output:')
output = torch.orgqr(input, tau)
print(output)
print('output.size()')
print(output.size())