'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.vander\ntorch.vander(x, N=None, increasing=False)\n'
import torch
x = torch.arange(1, 3, dtype=torch.float)
print('x = ', x)
y = torch.vander(x, 3, increasing=True)
print('y = ', y)
y = torch.vander(x, 3, increasing=False)
print('y = ', y)
y = torch.vander(x, 2, increasing=True)
print('y = ', y)
y = torch.vander(x, 2, increasing=False)
print('y = ', y)
y = torch.vander(x, 1, increasing=True)
print('y = ', y)
y = torch.vander(x, 1, increasing=False)
print('y = ', y)
y = torch.vander(x, 4, increasing=True)
print('y = ', y)
y = torch.vander(x, 4, increasing=False)
print('y = ', y)