'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.logspace\ntorch.logspace(start, end, steps, base=10.0, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)\n'
import torch
a = torch.logspace(start=0.1, end=2, steps=5, base=2)
print(a)
b = torch.zeros_like(a)
print(b)
c = torch.ones(5, 3)
print(c)
d = torch.zeros(3, 2)
print(d)
e = torch.ones(3, 2)
print(e)
f = torch.rand(3, 2)
print(f)
g = torch.rand(3, 2)
print(g)