input = torch.randn(3, 4)
q = torch.quantile(input, 0.5, dim=0)
q = torch.quantile(input, 0.5, dim=1, keepdim=True)
q = torch.quantile(input, 0.5, dim=(- 1), keepdim=True)
q = torch.quantile(input, 0.5, dim=None)
out = torch.empty(3)