'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.eye\ntorch.eye(n, m=None, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)\n'
import torch
input_data = torch.randn(4, 4)
print('Input data is: ', input_data)
eye_data = torch.eye(4, 4)
print('Eye data is: ', eye_data)
output = torch.mm(input_data, eye_data)
print('Output is: ', output)
output = torch.matmul(input_data, eye_data)
print('Output is: ', output)
output = (input_data @ eye_data)
print('Output is: ', output)
output = input_data.mm(eye_data)
print('Output is: ', output)
output = input_data.matmul(eye_data)