'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.utils.data.RandomSampler\ntorch.utils.data.RandomSampler(data_source, replacement=False, num_samples=None, generator=None)\n'
import torch
input_data = torch.randn(10, 3)
sampler = torch.utils.data.RandomSampler(input_data)
print(sampler)
print(list(sampler))
sampler = torch.utils.data.RandomSampler(input_data, replacement=True)
print(sampler)
print(list(sampler))
sampler = torch.utils.data.RandomSampler(input_data, replacement=True, num_samples=5)
print(sampler)
print(list(sampler))
sampler = torch.utils.data.RandomSampler(input_data, replacement=True, num_samples=5, generator=torch.Generator().manual_seed(1))
print(sampler)
print(list(sampler))