'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.atleast_2d\ntorch.atleast_2d(*tensors)\n'
import torch
x = torch.tensor(3.0)
y = torch.tensor(4.0)
z = torch.tensor(5.0)
x_2d = torch.atleast_2d(x)
y_2d = torch.atleast_2d(y)
z_2d = torch.atleast_2d(z)
print(x_2d)
print(y_2d)
print(z_2d)
print(x_2d.shape)
print(y_2d.shape)
print(z_2d.shape)
print(x.shape)
print(y.shape)
print(z.shape)
x_2d = x.view(1, 1)
y_2d = y.view(1, 1)
z_2d = z.view(1, 1)
print(x_2d)
print(y_2d)
print(z_2d)