'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.Tensor.put_\ntorch.Tensor.put_(_input_tensor, index, source, accumulate=False)\n'
import torch
input_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
print('input tensor: ', input_tensor)
index = torch.tensor([[0, 1], [1, 2]], dtype=torch.int64)
print('index: ', index)
source = torch.tensor([[10, 20], [30, 40]], dtype=torch.float32)
print('source: ', source)
input_tensor.put_(index, source, accumulate=False)
print('output tensor: ', input_tensor)
index = torch.tensor([[0, 1], [1, 2]], dtype=torch.int64)
print('index: ', index)
source = torch.tensor([[10, 20], [30, 40]], dtype=torch.float32)
print('source: ', source)
input_tensor.put_(index, source, accumulate=True)