
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = torch.nn.Linear(2, 2)
        self.linear2 = torch.nn.Linear(3, 3)

    def forward(self, x):
        v1  = x.permute(0, 2, 1) # Swap the second and third dimensions
        v1 = torch.cat([v1, v1], dim=1)  # Concatenate two tensors along the first dimension
        v1 = self.linear1(v1)  # Use linear transformation on the tensor with swapped second and third dimensions
        v2 = self.linear2(v1)  # Use linear transformation on a modified tensor generated by linear operation in Model constructor.
        return v2

# Initializing the model
m = Model()

