'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.random.manual_seed\ntorch.random.manual_seed(seed)\n'
import torch
data = torch.rand(4, 4)
print(data)
print()
torch.random.manual_seed(0)
data = torch.rand(4, 4)
print(data)
print()
torch.random.manual_seed(1)
data = torch.rand(4, 4)
print(data)
print()
torch.random.manual_seed(2)
data = torch.rand(4, 4)
print(data)
print()
torch.random.manual_seed(3)
data = torch.rand(4, 4)
print(data)
print()
torch.random.manual_seed(4)
data = torch.rand(4, 4)
print(data)
print()
torch.random.manual_seed(5)
data = torch.rand(4, 4)
print(data)
print()
torch.random.manual_seed(6)
data = torch.rand(4, 4)