'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.is_floating_point\ntorch.is_floating_point(input)\n'
import torch
x = torch.randn(4)
print(x)
print(torch.is_floating_point(x))
x = torch.tensor([1, 2, 3, 4], dtype=torch.float)
print(x)
print(torch.is_floating_point(x))
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
print(x)
print(torch.is_floating_point(x))
x = torch.tensor([1, 2, 3, 4], dtype=torch.float64)
print(x)
print(torch.is_floating_point(x))
x = torch.tensor([1, 2, 3, 4], dtype=torch.int)
print(x)
print(torch.is_floating_point(x))
x = torch.tensor([1, 2, 3, 4], dtype=torch.int8)
print(x)