
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv  = torch.nn.Conv2d(3, 8, 1)
 
    def forward(self, x1):
        v1  = self.conv(x1)
        v2  = torch.relu(v1) # Apply ReLU activation function to the output of conv operation (v1 here is a dummy name for input/output to conv layer). You are free to choose any name as long as it can be replaced.
        return v2

# Initializing the model
m  = Model()


# Inputs to the model
x1  = torch.randn(1, 3, 64, 64)
__output__  = m(x1) # __output__ is used here as a placeholder for input/output tensors that will be generated by PyTorch and replaced with actual values

