
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(1024, 512)
 
    def forward(self, x1):
        v1 = self.linear(x1)
        v2 = v1 + other
        return v2


# Initializing the model
m = Model()
 
# Inputs to the model
x1 = torch.randn(1000, 1024)
other  = torch.randn(1000, 512) # this tensor is not part of the model generated by you
__output__  = m(x1)

