
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv  = torch.nn.Conv2d(3, 8, 1, stride=1, padding=1)
 
    def forward(self, x1):
        v1  = self.conv(x1)
        v2  = v1  * 0.5
        v3  = v1 ** 2
        v4  = v3  * v1
        v5  = v4 + 0.7978845608028654 # This line is added and modified by the user to generate a different model from previous model
        v6  = v2  * torch.tanh(v5)
        return v6

# Initializing the model
m1  = Model()


# Inputs for the model_old, which are randomly generated by pytorch
x1  = torch.randn(1, 3, 64, 64)
__output__  = m1(x1)


