
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x1):
        v1 = torch.nn.functional.dropout(x1)  # Apply dropout to the input tensor

        # This is not a problem because this node will be erased by `replace_fx` and thus not included in the graph
        v2 = torch.rand_like(v1, dtype=torch.float32) 
        return v2


# Initializing the model
m = Model()


# Inputs to the model
x1  = torch.randn(50, 50).to(memory_format='channels_last')
x1 = torch.split(x1, [int(n*4) for n in range(.38,.7)], dim=2) # Split the input tensor into two tensors of size (n, 50, 20), and (n-n', 50, 30). Here 'n' is a variable representing the length of the input sequence. The variables are used to denote that these tensors are dynamically generated by user input.
