'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.greater\ntorch.greater(input, other, *, out=None)\n'
import torch
print('Task 1: import PyTorch')
print(('-' * 80))
print('PyTorch version: {}'.format(torch.__version__))
print('CUDA version: {}'.format(torch.version.cuda))
print('cuDNN version: {}'.format(torch.backends.cudnn.version()))
print(('-' * 80))
print('Task 2: Generate input data')
print(('-' * 80))
input = torch.randn(3, 3)
print('Input: \n{}'.format(input))
other = torch.randn(3, 3)
print('Other: \n{}'.format(other))
print(('-' * 80))
print('Task 3: Call the API torch.greater')
print(('-' * 80))
print('torch.greater(input, other, *, out=None)')
out = torch.greater(input, other)
print('Output: \n{}'.format(out))