'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.true_divide\ntorch.true_divide(dividend, divisor, *, out)\n'
import torch
x = torch.randn(3, requires_grad=True)
y = torch.randn(3, requires_grad=True)
z = torch.randn(3, requires_grad=True)
q = torch.true_divide(x, y)
r = torch.true_divide(x, z)
print('x:', x)
print('y:', y)
print('z:', z)
print('q:', q)
print('r:', r)
q_out = torch.empty(3)
r_out = torch.empty(3)
torch.true_divide(x, y, out=q_out)
torch.true_divide(x, z, out=r_out)
print('q_out:', q_out)
print('r_out:', r_out)