
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
 
    def forward(self, x1, y1, z1, w1, x2, y2, z2, w2):  # Arguments 8
        t1 = torch.mm(x1, y1)
        t2 = torch.mm(z1, w1)
        t3 = t1 + t2
        return t3


# Initializing the model
m = Model()

# Inputs to the model
x1  = torch.randn(4, 5).float()
y1  = torch.randn(5, 6).float()
z1  = torch.randn(7, 8).float()
w1  = torch.randn(9, 10).float()
x2  = torch.randn(4, 5).float()
y2  = torch.randn(5, 6).float()
z2  = torch.randn(7, 8).float()
w2  = torch.randn(9, 10).float()

 # Adding the initial input tensor and the arguments that are used in the pattern: x,y,z,w to form a larger tensor for model 
full_input  = torch.cat([x1, y1, z1, w1, x2, y2, z2, w2], dim=0)

 # The full_input is fed as input into the model along with __output__ as a target to be predicted. 
model_output = m(full_input)

# Target of model_output is the concatenation of results of matrix multiplication and additions
target1 = torch.cat([x1 @ y1, z1 @ w1], dim=0)
target2 = x2 @ y2 + z2 @ w2

 # The output of model should be close to the target generated by the model. 
assert torch.norm(model_output - target1)/torch.norm(target1) < 5e-3
assert torch.norm(model_output - target2)/torch.norm(target2) < 5e-3