
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, input1, input2, input3, input4): 
        v1 = torch.mm(input1, input2) # Matrix multiplication between the two inputs
        v2 = torch.mm(input3, input4) # Matrix multiplication of a third and fourth inputs

        return v1 + v2

# Initializing the model with two matrices that can be randomly generated by torch.randn
model  = Model()

i1 = torch.rand(50, 50)
i2 = torch.rand(50, 70)
m1 = i1 @ i2 # Matrix multiplication between these matrices

i3 = torch.rand(80, 40)
i4 = torch.rand(90, 60)
m2 = i3 @ i4 # Matrix multiplication of the first and second inputs generated by torch.randn 

# Inputs to the model (randomly generated inputs based on the previous matrices)
__output__1  = m1 + m2

