'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.Tensor.view\ntorch.Tensor.view(_input_tensor, *shape)\n'
import torch
print('Task 1: import PyTorch')
print('Task 2: Generate input data')
_input_tensor = torch.rand(2, 3)
print('Input tensor: ', _input_tensor)
print('Task 3: Call the API torch.Tensor.view')
_output_tensor = _input_tensor.view(3, 2)
print('Output tensor: ', _output_tensor)
print('\n==============')
print('Task 1: import PyTorch')
print('Task 2: Generate input data')
_input_tensor = torch.rand(2, 3)
print('Input tensor: ', _input_tensor)
print('Task 3: Call the API torch.Tensor.view')
_output_tensor = _input_tensor.view(6)
print('Output tensor: ', _output_tensor)
print('\n==============')
print('Task 1: import PyTorch')