'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.linspace\ntorch.linspace(start, end, steps, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)\n'
import torch
x = torch.linspace(start=0.0, end=10.0, steps=5)
print('x = ', x)
x = torch.linspace(start=0.0, end=10.0, steps=10)
print('x = ', x)
x = torch.linspace(start=0.0, end=10.0, steps=15)
print('x = ', x)
x = torch.linspace(start=0.0, end=10.0, steps=20)
print('x = ', x)
x = torch.linspace(start=0.0, end=10.0, steps=25)
print('x = ', x)
x = torch.linspace(start=0.0, end=10.0, steps=30)
print('x = ', x)
x = torch.linspace(start=0.0, end=10.0, steps=35)
print('x = ', x)