'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.linspace\ntorch.linspace(start, end, steps, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)\n'
import torch
x = torch.linspace(0, 1, steps=11)
y = torch.linspace(0, 1, steps=11)
print(x)
print(y)
x = torch.tensor(0.5)
y = torch.linspace(0, 1, steps=11)
print(x)
print(y)
x = torch.tensor([0.5])
y = torch.linspace(0, 1, steps=11)
print(x)
print(y)
x = torch.tensor([[0.5]])