
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
 
    def forward(self, q1, k1, v1):
        qk = torch.matmul(q1, k1) / inv_scale_factor 
        scaled_qk = qk + 1e-9
        softmax_qk = scaled_qk.softmax(-1) # -1 is the dim
        dropout_qk = torch.nn.functional.dropout(softmax_qk, p=0.25)  
        output = dropout_qk @ v1
        return output


# Initializing the model
m  = Model()


# Inputs to the model
q1  = torch.randn(8, 3, 64, 64) # query for the first model
k1  = torch.randn(8, 729, 3200) * 0.5 # key and value for the first model
v1  = torch.rand(729, 8) / 2 + 0.5 


# Running the model with input tensors generated by you
__output_1__  = m(q1, k1, v1).sum()

