
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.convt = torch.nn.ConvTranspose2d(8, 3, 1, stride=1, padding=0)
 
    def forward(self, x1):
        v1  = self.convt(x1) 
        v2  = v1 + 3 # Add 3 to the output of the transposed convolution
        v3  = torch.clamp(v2, min=0)  # Clamp the output of the addition operation to a minimum of `0`
        v4  = torch.clamp(v3, max=6)  # Clamp the output of the previous clamp operation to a maximum of `6`
        v5  = v1 * v4 # Multiply the output of the transposed convolution by the output of the clamp operation
        v6  = v5 / 6 # Divide the output of the multiplication operation by 6 
        return v6

# Initializing the model
m = Model()

# Inputs to the model. This example uses the input generated by https://pytorch.org/docs/stable/generated/torch.randn.html?highlight=torch%20randn
x1 = torch.tensor([[[[-1.5396,   -0.8047 ,  -1.7377],
                     [ 1.1313 ,   0.1557  , -1.058 ]]]])

# Running the model on the input tensor. The model output should be close to the original PyTorch model’s output.
