'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.reshape\ntorch.reshape(input, shape)\n'
import torch
x = torch.randn(1, 2, 3, 4)
print('x.shape:', x.shape)
print('x:', x)
y = torch.reshape(x, ((- 1), 3, 4))
print('y.shape:', y.shape)
print('y:', y)
y = torch.reshape(x, (2, 3, 4))
print('y.shape:', y.shape)
print('y:', y)
y = torch.reshape(x, (1, 6, 4))
print('y.shape:', y.shape)
print('y:', y)
y = torch.reshape(x, (1, 3, 8))
print('y.shape:', y.shape)
print('y:', y)
y = torch.reshape(x, (1, 24))
print('y.shape:', y.shape)