
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
 
    def forward(self, x1):
        v0  = torch.linspace(-5.0, 5.0 , steps=x1).unsqueeze(2) # Start from -5 until 5
        v1  = self.linear(v0) > 0 # A boolean tensor to identify where the values in the linear transformation are greater than 0
        v2  = x1 * negative_slope # Multiply each value in the input by a negative slope
        v3  = torch.where(v1, x1, v2) # If each element of v1 is True choose its corresponding element from v0, otherwise choose its corresponding element from v2
        return v3


# Initializing the model
m  = Model()
 
 # Inputs to the model
x1 = torch.linspace(-5.0 , 5.0 , steps=4)
 
# Outputs of the model on the input tensors generated by the system for each scenario described in the requirements:
__output__  = m(x1)