'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.fft.fftfreq\ntorch.fft.fftfreq(n, d=1.0, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)\n'
import torch
print(torch.__version__)
x = torch.arange(10)
print(x)
freq = torch.fft.fftfreq(x.size()[0])
print(freq)
y = torch.fft.fft(x)
print(y)
z = torch.fft.ifft(y)
print(z)
freq_shift = torch.fft.fftshift(freq)
print(freq_shift)
freq_shift_reverse = torch.fft.ifftshift(freq_shift)
print(freq_shift_reverse)