'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.Tensor.prod\ntorch.Tensor.prod(_input_tensor, dim=None, keepdim=False, dtype=None)\n'
import torch
_input_tensor = torch.randn(2, 3)
print('Input tensor:')
print(_input_tensor)
print('Output tensor:')
print(_input_tensor.prod())
print('Output tensor:')
print(_input_tensor.prod(dim=0))
print('Output tensor:')
print(_input_tensor.prod(dim=1))
print('Output tensor:')
print(_input_tensor.prod(dim=1, keepdim=True))
print('Output tensor:')
print(_input_tensor.prod(dim=1, keepdim=True, dtype=torch.int))