"\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.nn.functional.poisson_nll_loss\ntorch.nn.functional.poisson_nll_loss(input, target, log_input=True, full=False, size_average=None, eps=1e-08, reduce=None, reduction='mean')\n"
import torch
import torch.nn as nn
import torch.nn.functional as F
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
loss = F.poisson_nll_loss(input, target, log_input=True, full=False, size_average=None, eps=1e-08, reduce=None, reduction='mean')
print(loss)
print(loss.item())
print(loss.size())
print(loss.shape)
print(loss.dim())
print(loss.dtype)
print(loss.device)
print(loss.requires_grad)
print(loss.grad_fn)
print(loss.is_leaf)
print(loss.grad)
print(loss.data)
print(loss.data.shape)
print(loss.data.dim())
print(loss.data.dtype)
print(loss.data.device)
print(loss.data.requires_grad)
print(loss.data.grad_fn)