'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.diagonal\ntorch.diagonal(input, offset=0, dim1=0, dim2=1)\n'
import torch
input = torch.rand(3, 3)
print(input)
output = torch.diagonal(input)
print(output)
output = torch.diagonal(input, offset=1)
print(output)
output = torch.diagonal(input, offset=(- 1))
print(output)
input = torch.rand(3, 3, 3)
print(input)
output = torch.diagonal(input, dim1=1, dim2=2)
print(output)
input = torch.rand(3, 3, 3, 3)
print(input)
output = torch.diagonal(input, dim1=1, dim2=3)
print(output)