'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.all\ntorch.all(input, dim, keepdim=False, *, out=None)\n'
import torch
print(torch.__version__)
input = torch.randn(3, 4)
print(input)
output = torch.all((input > 0))
print(output)
output = torch.all((input > 0), dim=0)
print(output)
output = torch.all((input > 0), dim=1)
print(output)
output = torch.all((input > 0), dim=1, keepdim=True)
print(output)
output = torch.all((input > 0), dim=(- 1))
print(output)
output = torch.all((input > 0), dim=(- 1), keepdim=True)
print(output)