'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.all\ntorch.all(input, dim, keepdim=False, *, out=None)\n'
import torch
a = torch.randn(2, 3)
print(a)
print(torch.all((a > 0)))
print(torch.all((a > 0), dim=0))
print(torch.all((a > 0), dim=1))
print(torch.all((a > 0), dim=1, keepdim=True))
a = torch.tensor([[True, True], [False, False]])
print(a)
print(torch.all(a))
print(torch.all(a, dim=0))
print(torch.all(a, dim=1))
print(torch.all(a, dim=1, keepdim=True))
a = torch.tensor([[True, True], [True, False]])
print(a)
print(torch.all(a))
print(torch.all(a, dim=0))
print(torch.all(a, dim=1))
print(torch.all(a, dim=1, keepdim=True))