
class Model(torch.nn.Module):
    def __init__(self, min_value=0., max_value=1.):
        super().__init__()
        self.conv = torch.nn.Conv2d(3, 8, 1, stride=1, padding=1)
 
    def forward(self, x1):
        v1 = self.conv(x1)
        v2 = torch.clamp_min(v1, min_value)
        v3 = torch.clamp_max(v2, max_value)
        return v6


# Input to the model
__input__ = torch.randn(1, 3, 64, 64)

# Description of requirements
The clamping function can be either `torch.nn.functional.clamp` or `torch.clamp`. Please make sure that both functions are called with keyword arguments in order to correctly perform the clamp operation: `min_value` and `max_value`. The inputs for the two functions are different, and the inputs should be generated by `torch.randn()` with appropriate shapes for the input tensors `x1`, `v2`, and `v3`.


# Validation
Please generate examples that meet both requirements in your submission file and upload them to D2L CoLab to ensure code quality. The model should also contain valid input tensor(s) (see Input).


