'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.polygamma\ntorch.polygamma(n, input, *, out=None)\n'
import torch
input = torch.randn(4, 4)
print(torch.polygamma(0, input))
print(torch.polygamma(1, input))
print(torch.polygamma(2, input))
print(torch.polygamma(3, input))
print(torch.polygamma(4, input))
print(torch.polygamma(5, input))
print(torch.polygamma(6, input))
print(torch.polygamma(7, input))
print(torch.polygamma(8, input))
print(torch.polygamma(9, input))
print(torch.polygamma(10, input))
print(torch.polygamma(11, input))
print(torch.polygamma(12, input))
print(torch.polygamma(13, input))
print(torch.polygamma(14, input))
print(torch.polygamma(15, input))
print(torch.polygamma(16, input))