
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(16384, 5)
 
    def forward(self, x1):
        v2 = self.linear(x1) + self.other # Apply the linear transformation to an input tensor and then add another tensor to the output of the linear transformation (self.other is specified as a keyword argument here.)
        return v2
 
m  = Model()


# Initializing the model
m.other  = torch.randn(16384, 5) # This line adds an attribute 'other' to your module; its initial value is randomly generated by torch.

# Inputs to the model
x1  = torch.randn(200, 16384)
__output__  = m(x1)

