'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.ne\ntorch.ne(input, other, *, out=None)\n'
import torch
input = torch.randn(2, 3)
other = torch.randn(2, 3)
print(input)
print(other)
ne = torch.ne(input, other, out=None)
print(ne)
print(('-' * 100))
ne = torch.ne(input, other, out=None)
print(ne)
print(('-' * 100))
ne = torch.ne(input, other, out=None)
print(ne)
print(('-' * 100))
ne = torch.ne(input, other, out=None)
print(ne)