
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(3, 8)
 
    def forward(self, x1):
        v1  = self.linear(x1)
        v2  = torch.tanh(v1) # Apply hyperbolic tangent function to the output of linear transformation
        return v2


# Initializing the model
m  = Model()
 
# Input tensor for the model example with the same format as the input tensor generated by user_example.py:
inputTensor = torch.tensor([[-0.4371,  0.5832 , -0.5296],
 [ 0.6439,  0.2030 , -0.5324],
 [-0.7142,  0.4376 ,  0.0306]])

# Output of the model with inputTensor as an argument:
output = m(inputTensor)


# Initializing the input tensor based on the format generated by user_example.py 
inputTensor = torch.randn(2, 3)

# Applying the model to the inputTensor
