'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.prod\ntorch.prod(input, dim, keepdim=False, *, dtype=None)\n'
import torch
x = torch.randint(10, (3, 3))
print(x)
torch.prod(x, dim=0)
torch.prod(x, dim=1)
torch.prod(x, dim=0, keepdim=True)
torch.prod(x, dim=1, keepdim=True)
x = torch.randint(10, (3, 3, 3))
print(x)
torch.prod(x, dim=0)
torch.prod(x, dim=1)
torch.prod(x, dim=2)
torch.prod(x, dim=0, keepdim=True)
torch.prod(x, dim=1, keepdim=True)