
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(2, 3)

    def forward(self, x1, x2):
        v1 = torch.cat([x1, x2], dim=0) # Concatenate tensors along a dimension (dimension 0 in this example).
        v2 = v1.view(-1, 3) # Reshape the concatenated tensor (-1 means "unspecified". It is not -1 here.)
        return torch.relu(v2), self.linear


# Initializing the model
m  = Model()

# Input tensors for the model (not the first parameter in the forward function of this model, but they are used to call the forward function)
__input0__  = torch.randn(3, 1024) # This tensor is the input of the model. It should not be a model parameter.
__input1__  = torch.randn(5, 1024)


# Outputs from the model. We expect these outputs should match the following statements that are generated by the code analyser after sinking the `cat_after_pointwise` optimization:
__output__, __linear__ = m(__input0__, __input1__)