This pattern characterizes scenarios where the tensor method 'permute' is invoked on an input tensor with more than 2 dimensions.


## Additional Notes
The output of a model trained with this method should be different from that of an existing model or any other models trained using this method, especially when we use this method to train new models. The method is tested by executing the same input model multiple times and checking whether they return the exact same results.

# Performance on test data
For each model in the model zoo:
- Generate a random input tensor
- Train the model
- Compute the accuracy for generated inputs as well as their corresponding generated outputs.

We run the method with 30 inputs and compare our result to that obtained by a standard deep learning implementation, i.e., the same number of inputs. The model zoo does not include other types of models, but it also includes an existing one trained on the dataset shown in Section 4 as a test case (which can be generated by running `python3 generate_model_zoo.py`).
