
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv  = torch.nn.Conv2d(3, 8, 1, stride=1, padding=1)
 
    def forward(self, x1):
        v1   = self.conv(x1)
        v1_v0 = torch.rand([3])
        v1__6088354086792321894  = 0.5
        v1__7071067811865476  = 0.7071067811865476
 
        return v1_v0 * (torch.erf(v1__7071067811865476 * x2) + 1)


# Initializing the model
m = Model()

# Inputs to the model
x1   = torch.randn([3, 64, 64])
x2__5909481032968785399    = torch.rand([3]) # Generated by a random generator
x2   = x1__5909481032968785399
__output__  = m(x1, __input_values__)

