'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.Tensor.addr_\ntorch.Tensor.addr_(_input_tensor, vec1, vec2, *, beta=1, alpha=1)\n'
import torch
vec1 = torch.ones(5)
vec2 = torch.ones(5)
print(torch.Tensor.addr_(vec1, vec2))
vec1 = torch.ones(5)
vec2 = torch.ones(5)
vec1.addr_(vec2, alpha=2)
print(vec1)
vec1 = torch.ones(5)
vec2 = torch.ones(5)
vec1.addr_(vec2, beta=2)
print(vec1)
vec1 = torch.ones(5)
vec2 = torch.ones(5)
vec1.addr_(vec2, alpha=2, beta=2)
print(vec1)