'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.set_warn_always\ntorch.set_warn_always(b)\n'
import torch
x = torch.randn(2, 2)
y = torch.randn(2, 2)
torch.set_warn_always(True)
print((x + y))
print((x * y))
print((x / y))
print((x - y))
print((x ** 2))
print((x % 2))
torch.set_warn_always(False)
print((x + y))
print((x * y))
print((x / y))
print((x - y))
print((x ** 2))
print((x % 2))
torch.set_warn_always(True)
print((x + y))
print((x * y))
print((x / y))
print((x - y))
print((x ** 2))
print((x % 2))