
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.attn = torch.nn.MultiheadAttention(10, 8)
 
    def forward(self, query: torch.Tensor, key: torch.Tensor, value: torch.Tensor):
        attn_weight = self.attn(query, key, value)[0]
 
        # We add a dropout layer here to make the model more robust in case of overfitting
        attn_weight = torch.dropout(attn_weight, 0.5)
        output = attn_weight @ value
        return output


# Initializing the model
m = Model()

# Inputs to the model (in this case, query and key are the same tensor because we are applying self-attention, so no need for the third argument). We have also used a masked softmax with dropout probability of 0.5 here, but that can be generated by a random number generator.
query = torch.randn(4321, 8)
key   = query
value = torch.randn(4321, 768)
 
__output__  = m(query, key, value)

