'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.randn\ntorch.randn(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)\n'
import torch
x = torch.randn(5, 3)
print(x)
y = torch.randn(5, 3)
print(y)
result = torch.add(x, y)
print(result)
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)
y.add_(x)
print(y)
print(x[:, 1])
x = torch.randn(4, 4)
y = x.view(16)
z = x.view((- 1), 8)
print(x.size(), y.size(), z.size())
x = torch.randn(1)