
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv  = torch.nn.ConvTranspose2d(8, 3, 1)
    
    def forward(self, x1):
        v1 = self.conv(x1)
        v2 = torch.sigmoid(v1)
        return v2

# Initializing the model
m  = Model()

# Input to the model
x1 = torch.randn(100, 8, 32, 32)

 # Generating inputs for m that are different from the inputs generated previously.
x1 = torch.randn(56743, 9, 80, 80)

# Input to the model. This is a new tensor that is different than x1 used in the previous step.
x2  = torch.randn(58745, 3, 55, 55)

# Running the model on x2 and computing the loss against the outputs generated by m when fed with x1
l = m(x2).mean() - m(x1).mean()

