'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.Tensor.movedim\ntorch.Tensor.movedim(_input_tensor, source, destination)\n'
import torch
input_tensor = torch.rand(2, 3, 4)
print('Input Tensor:')
print(input_tensor)
print('Test 1:')
output_tensor = input_tensor.movedim(0, 2)
print('Output Tensor:')
print(output_tensor)
print('Test 2:')
output_tensor = input_tensor.movedim(1, 2)
print('Output Tensor:')
print(output_tensor)
print('Test 3:')
output_tensor = input_tensor.movedim(2, 0)
print('Output Tensor:')
print(output_tensor)
print('Test 4:')