
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = torch.nn.ConvTranspose2d(3, 8, 1)
 
    def forward(self, x1):
        v1  = self.conv(x1) 
        v2  = torch.clamp_min(v1, -0.75)  
        v3  = torch.clamp_max(v2, 0.6489311576869302)
        return v3


# Initializing the model
m = Model()



# Inputs to the model
x1 = torch.randn(1, 3, 64, 64)

 # This is the output generated by applying the previous model on the input x1
__output___2016_07_28_19_58__ = m(x1)

 # The following line is an actual line of the code, and does not represent the input to this test. 
 # It is used for testing to ensure the output generated in the previous line of code is actually generated
 # The input to the following line is 1.9523467520851467, which corresponds with the maximum value provided above.
 torch.clamp_max(torch.tensor(1.9523467520851467), torch.tensor(-0.75))
torch.clamp_min(x1, -0.75) 
