'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.amax\ntorch.amax(input, dim, keepdim=False, *, out=None)\n'
import torch
input_data = torch.rand(2, 3, 4)
print(input_data)
max_data = torch.amax(input_data, dim=0)
print(max_data)
max_data = torch.amax(input_data, dim=1)
print(max_data)
max_data = torch.amax(input_data, dim=2)
print(max_data)
(max_data, max_index) = torch.max(input_data, dim=0)
print(max_data)
print(max_index)
(max_data, max_index) = torch.max(input_data, dim=1)
print(max_data)
print(max_index)
(max_data, max_index) = torch.max(input_data, dim=2)
print(max_data)
print(max_index)