'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.use_deterministic_algorithms\ntorch.use_deterministic_algorithms(mode)\n'
import torch
x = torch.randn(2, 2)
y = torch.randn(2, 2)
torch.use_deterministic_algorithms(True)
z = (x + y)
print(z)
torch.use_deterministic_algorithms(False)
z = (x + y)
print(z)
torch.use_deterministic_algorithms(True)
z = (x + y)
print(z)
torch.use_deterministic_algorithms(False)
z = (x + y)
print(z)
torch.use_deterministic_algorithms(True)
z = (x + y)
print(z)