'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.lt\ntorch.lt(input, other, *, out=None)\n'
import torch
input = torch.randn(3)
other = torch.randn(3)
print(torch.lt(input, other))
print(torch.lt(input, other, out=input))
print(input)
print(torch.le(input, other))
print(torch.le(input, other, out=input))
print(input)
print(torch.gt(input, other))
print(torch.gt(input, other, out=input))
print(input)
print(torch.ge(input, other))
print(torch.ge(input, other, out=input))
print(input)
print(torch.eq(input, other))
print(torch.eq(input, other, out=input))
print(input)