'\nTask 1: import PyTorch\nTask 2: Generate input data\nTask 3: Call the API torch.linalg.pinv\ntorch.linalg.pinv(A, rcond=1e-15, hermitian=False, *, out=None)\n'
import torch
A = torch.randn(2, 3, requires_grad=True)
print('A =', A)
B = torch.linalg.pinv(A)
print('B =', B)
print('B.requires_grad', B.requires_grad)
print('B.grad', B.grad)
print('A.requires_grad', A.requires_grad)
print('A.grad', A.grad)
print('B.requires_grad_()', B.requires_grad_())
print('B.grad', B.grad)
print('A.requires_grad_()', A.requires_grad_())
print('A.grad', A.grad)
print('B.requires_grad', B.requires_grad)
print('B.grad', B.grad)
print('A.requires_grad', A.requires_grad)
print('A.grad', A.grad)
print('B.requires_grad_()', B.requires_grad_())